//spring.application.name=quickbite

# application_example.properties 

spring.datasource.url=jdbc:mysql://HOST:PORT/DATABASE
spring.datasource.username=DB_USER
spring.datasource.password=DB_PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=false

jwt.secret=YOUR_JWT_SECRET_HERE
server.port=8080